### ISSUE TITLE
Dot color changes twice on page swap

### ISSUE THREAD

**Issue by frindaddy** [frindaddy/mixd#19] opened 2023-12-27 04:19 UTC
The code to randomize the dot color in the logo seems to run twice when the page is refreshed or the user moves to a new page. You can see the dot change colors, then very quickly change again.

I have no idea why this happens

**Comment by sidezbros** [comment] 2023-12-27 21:34
I spent a decent amount of time working on this. I made a small patch in v1.3.1 to help address it. The useEffect was dependent on the variable it was changing so it was causing some flashing as it recursively called itself. This change seems to fix the bug listed in this issue so I am marking it as closed. That said, the user can still see the dot changing color after a slight delay when returning from a drink page. This is due to the refresh of App.js and is not easily solved.

**Comment by frindaddy** [comment] 2024-09-26 01:23
Fixed on page refresh. Still does not work on page switch (e.g. list to drink entry back to list)

**Comment by sidezbros** [comment] 2024-10-04 18:53
The remaining flickering was a side effect of system wide stutter caused by the page reloading on navigation. This has been resolved in PR #50

**Closed by sidezbros** 2024-10-04 18:53 UTC
Labels: bug
